name: StaleBot
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
jobs:
  StaleBot:
    runs-on: ubuntu-latest
    permissions:
      issues: write # actions/stale@v8.0.0
      pull-requests: write # actions/stale@v8.0.0
    if: github.repository == 'aws/karpenter-provider-aws'
    name: Stale issue bot
    steps:
      # PR stale-out
      - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v9.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          only-issue-labels: 'ignore' # Ignore this step for Issues
          stale-pr-message: 'This PR has been inactive for 14 days. StaleBot will close this stale PR after 14 more days of inactivity.'
          exempt-pr-labels: 'blocked,needs-review,needs-design'
          stale-pr-label: 'lifecycle/stale'
          close-pr-label: 'lifecycle/closed'
          days-before-stale: 14
          days-before-close: 14
          operations-per-run: 300
      # Issue stale-out for "triage/needs-information"
      - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v9.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been inactive for 14 days. StaleBot will close this stale issue after 14 more days of inactivity.'
          only-issue-labels: 'triage/needs-information'
          stale-issue-label: 'lifecycle/stale'
          close-issue-label: 'lifecycle/closed'
          only-pr-labels: 'ignore' # Ignore this step for PRs
          days-before-stale: 14
          days-before-close: 14
          operations-per-run: 300
      # Issue stale-out for "triage/solved"
      - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v9.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been inactive for 7 days and is marked as "triage/solved". StaleBot will close this stale issue after 7 more days of inactivity.'
          only-issue-labels: 'triage/solved'
          stale-issue-label: 'lifecycle/stale'
          close-issue-label: 'lifecycle/closed'
          only-pr-labels: 'ignore' # Ignore this step for PRs
          days-before-stale: 7
          days-before-close: 7
          operations-per-run: 300
